### ISSUE TITLE
Hang/freeze in combat (sfall 4.2.5.2-extended)

### ISSUE THREAD

**Issue by ghost** [FalloutTeamX/sfall-Extended#38] opened 2020-06-20 11:37 UTC
Hi. fan of your work. Got itch to play some fo2 again and this happened.
Game hangs during combat after deathclaws get summoned and its their turn to attack.
this seems to happen only with 4.2.5.2 version. I tried 4.2.5.1 with no problems.

![Untitled](https://user-images.githubusercontent.com/31844071/85200791-e2869a00-b302-11ea-924e-d9a1be652862.png)
[Savefiles](https://github.com/FakelsHub/sFall-Extended/files/4807791/SLOT09.zip)
vanilla 1.02US(patch000.dat)

**Comment by NovaRain** [comment] 2020-06-20 23:17
The freeze seems kinda random, as in one of my tests the game hanged at fire geckos, and in another test it only hanged until giant rats. But deathclaws can trigger it rather easily.

EDIT: the cause might be the attempt to optimize combat_is_shot_blocked_ in Bugfixes.cpp in commit c7759d6.
If I commented out `SafeWriteBytes(0x426D60, (BYTE*)&data, 6);` I can kill all summoned critters with no problem.

**Comment by Lexx2k** [comment] 2020-06-21 01:04
I also had a crash in ettu in an encounter a few days ago. Seems to be related to critters trying to attack the player?

Maybe related to the recent ai changes or something? Never had a crash when critters try to attack the player before updating to latest sfall stable.

**Comment by FakelsHub** [comment] 2020-06-25 12:31
I just noticed this Issue.

> If I commented out `SafeWriteBytes(0x426D60, (BYTE*)&data, 6);` I can kill all summoned critters with no problem.

Then can make a fix for this and release a new version 4.2.6, or continue with 4.2.5.3 (4.2.5.2 for you) ?
I still don't plan any other changes to sfall.

**Comment by NovaRain** [comment] 2020-06-25 14:00
> Then can make a fix for this and release a new version 4.2.6, or continue with 4.2.5.3 (4.2.5.2 for you) ?
> I still don't plan any other changes to sfall.

The current official release doesn't contain the code, so there's no urgent need for me to release hotfix for the official build. Maybe you can just release a hotfix 4.2.5.3 with only the code commented out, and leave the rest of changes to next 4.2.6 release, as the recent commits are all minor ones IMO. I guess the freeze is similar to the infinite loop (keep building path to the same critter) that you tried to prevent in previous commits?

**Comment by FakelsHub** [comment] 2020-06-26 23:45
> Maybe you can just release a hotfix 4.2.5.3 with only the code commented out, and leave the rest of changes to next 4.2.6 release, as the recent commits are all minor ones IMO. 

I think we should release 4.2.6 with a few fixes later(at end) this month.

**Closed as completed** 2020-06-28 13:17 UTC
Labels: Bug
